---
- name: m4 wget 
  shell: wget http://ftp.gnu.org/gnu/m4/m4-1.4.16.tar.gz chdir=/usr/local/src 
  sudo: yes
  tags: m4

- name: m4-uncommpress
  shell: tar zxvf m4-1.4.16.tar.gz chdir=/usr/local/src
  sudo: yes
  tags: m4  

- name: m4 install
  shell: ./configure --prefix=/usr/local/ chdir=/usr/local/src  
  sudo: yes
  tags: m4  

- name: m4 install2
  shell: make chdir=/usr/local/src  
  sudo: yes
  tags: m4  

- name: m4 install3
  shell: make install chdir=/usr/local/src  
  sudo: yes
  tags: m4  

- name: autoconf wget 
  shell: wget http://ftp.gnu.org/gnu/autoconf/autoconf-latest.tar.gz  
  sudo: yes
  tags: autoconf

- name: autoconf-uncommpress
  shell: tar xfvz autoconf-latest.tar.gz  
  sudo: yes
  tags: autoconf  

- name: autoconf-install
  shell: ./configure && make && make install chdir=/home/ec2-user/autoconf-2.69  
  sudo: yes
  tags: autoconf  

- name: boost wget
  shell: wget wget http://sourceforge.net/projects/boost/files/boost/1.59.0/boost_1_59_0.zip
  tags: boost 

- name: boost unzip 
  shell: unzip boost_1_59_0.zip
  tags: boost 

- name: boost-install
  shell: ./bootstrap.sh && ./b2 install -j4 chdir=`pwd`/boost_1_59_0 
  sudo: yes
  tags: boost  
